import type { Metadata } from "next";
import { Kanit } from "next/font/google"; // <-- เพิ่มตรงนี้
import "./globals.css";

const kanit = Kanit({
  variable: "--font-kanit", // <-- ตั้งชื่อ custom property
  subsets: ["thai", "latin"], // <-- ถ้าต้องรองรับภาษาไทยด้วย
  weight: ["300", "400", "500", "700"], // <-- กำหนดน้ำหนักที่ต้องใช้
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${kanit.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
